export const email = 'jayapriyaa02@gmail.com';

export const capabilities = [
  { name: 'SEO & AI Search', short: 'SEO', label: 'Build discoverability', metric: '2,500+', result: 'product pages optimized', description: 'Technical SEO, keyword strategy, and on-page optimization that make the right products easier to find.', steps: ['Technical & content audit', 'Keyword and search-intent mapping', 'Metadata, copy & internal linking', 'Measurement & iteration'], tools: 'Ahrefs / Semrush / Search Console' },
  { name: 'Content & Demand gen', short: 'Content', label: 'Create demand', metric: '35', result: 'webinar sign-ups in 14 days', description: 'Useful stories built for people and search engines. From SEO blogs to website copy, social content, and personal branding.', steps: ['Audience & topic research', 'Editorial strategy', 'Create, optimize & distribute', 'Learn from engagement'], tools: 'WordPress / Canva / Blog & social content' },
  { name: 'Performance marketing', short: 'Paid', label: 'Convert intent', metric: '800+', result: 'qualified leads in 60 days', description: 'Focused Meta and Google Ads campaigns, with creative testing and conversion tracking built into the process.', steps: ['Audience & offer strategy', 'Campaign and creative setup', 'A/B testing & optimization', 'Lead quality & conversion analysis'], tools: 'Google Ads / Meta Ads / Analytics' },
  { name: 'B2B & outreach', short: 'B2B', label: 'Start conversations', metric: '80+', result: 'B2B leads, organically', description: 'LinkedIn prospecting and personalized email sequences that connect relevant offers with the people who make decisions.', steps: ['Ideal customer profiling', 'Prospect research', 'Personalized outreach & follow-ups', 'Qualify & nurture'], tools: 'LinkedIn / Email / Apollo.io / Clay / HeyReach' },
  { name: 'AI & automation', short: 'AI + Auto', label: 'Connect the system', metric: 'One', result: 'connected growth system', description: 'Practical AI and connected workflows that remove repetitive work and give marketing teams more room to think.', steps: ['Map the manual workflow', 'Connect data & tools', 'Build, test & monitor', 'Keep a human in the loop'], tools: 'n8n / Make.com / AI tools / CRM workflows' },
];

export const projects = [
  { id: 'seo', category: 'SEO', company: 'FirstHub Ecom', title: 'Making 2,500 products discoverable.', metric: '2,500+', label: 'products optimized', theme: 'orange', summary: 'A stronger search foundation. A healthier website. More room to grow.', challenge: 'A large product catalog needed consistent on-page optimization and a stronger technical foundation to improve organic discovery.', approach: ['Researched product keywords and mapped search intent.', 'Reworked product titles, descriptions, metadata, and on-page content.', 'Improved technical site health and tracked authority over time.'], outcomes: [['19 → 96', 'Website health'], ['11 → 24', 'Domain authority'], ['10×', 'Online sales growth']], note: 'Results from the FirstHub Ecom engagement. The sales result reflects the wider marketing effort, not SEO alone.' },
  { id: 'paid', category: 'Performance', company: 'Coderead', title: 'The right audience. Real acquisition.', metric: '800+', label: 'qualified leads in 60 days', theme: 'dark', summary: 'Turning Meta Ads into a focused customer acquisition engine.', challenge: 'Generate a qualified lead pipeline quickly, while continuously improving campaign relevance and conversion performance.', approach: ['Built audience segments and campaign structures on Meta Ads.', 'Tested messaging and creative against audience intent.', 'Monitored cost per lead and conversion rates to guide budget and campaign decisions.'], outcomes: [['800+', 'Qualified leads'], ['60 days', 'Acquisition sprint'], ['Meta Ads', 'Paid platform']], note: 'Results from the Coderead performance marketing engagement.' },
  { id: 'b2b', category: 'B2B', company: 'Cogent Innovation', title: 'Conversations that become opportunities.', metric: '80+', label: 'organic B2B leads', theme: 'blue', summary: 'A repeatable LinkedIn and email outreach system, built around relevance.', challenge: 'Reach relevant business decision-makers and create opportunities through organic outreach.', approach: ['Defined ideal customer profiles and researched decision-makers.', 'Combined LinkedIn content and personalized outreach.', 'Created email sequences and follow-ups to nurture interest.'], outcomes: [['80+', 'B2B leads'], ['Organic', 'LinkedIn acquisition'], ['LinkedIn + Email', 'Outreach channels']], note: 'LinkedIn outreach and lead generation results from the portfolio’s reported work.' },
];

export const process = [
  { title: 'Understand', description: 'Start with the business, the audience, and the gap between where you are and where you want to be.', detail: 'Audience research · Competitor analysis · Marketing audit' },
  { title: 'Strategize', description: 'Build a connected plan around customer intent, channel fit, and a clear definition of success.', detail: 'Channel strategy · Customer journey · Success metrics' },
  { title: 'Execute', description: 'Bring the strategy to life through thoughtful content, targeted campaigns, and connected workflows.', detail: 'Content production · Campaign launch · Workflow setup' },
  { title: 'Measure', description: 'Track the outcomes that matter. Look beyond reach to understand lead quality, conversions, and business impact.', detail: 'Analytics · Attribution · Conversion reporting' },
  { title: 'Optimize', description: 'Use what the data teaches us to improve the next creative, campaign, and customer experience.', detail: 'Experimentation · Iteration · Sustainable growth' },
];
